import { ComponentDoc, Config } from '../config/schema.js';
import Handlebars from 'handlebars';
import fs from 'fs/promises';
import path from 'path';

// Register Handlebars helpers
Handlebars.registerHelper('escapeType', (type: string) => {
  return type.replace(/\|/g, '\\|').replace(/</g, '&lt;').replace(/>/g, '&gt;');
});

Handlebars.registerHelper('formatCode', (code: string) => {
  return code.trim();
});

Handlebars.registerHelper('confidence', (value: number) => {
  if (value >= 0.8) return 'High';
  if (value >= 0.5) return 'Medium';
  return 'Low';
});

Handlebars.registerHelper('confidenceColor', (value: number) => {
  if (value >= 0.8) return 'green';
  if (value >= 0.5) return 'yellow';
  return 'red';
});

Handlebars.registerHelper('eq', (a: unknown, b: unknown) => a === b);
Handlebars.registerHelper('multiply', (a: number, b: number) => Math.round(a * b));
Handlebars.registerHelper('upperCase', (s: string) => s.toUpperCase());

const DEFAULT_TEMPLATE = `---
title: {{name}}
description: {{description}}
{{#if category}}category: {{category}}{{/if}}
---

import { Callout, Tab, Tabs } from 'nextra/components';

# {{#if displayName}}{{displayName}}{{else}}{{name}}{{/if}}

{{description}}

{{#if metadata.confidence}}
<Callout type="info">
  Documentation Confidence: **{{confidence metadata.confidence}}** ({{multiply metadata.confidence 100}}%)
</Callout>
{{/if}}

## Props

{{#if props.length}}
| Prop | Type | Required | Default | Description |
|------|------|----------|---------|-------------|
{{#each props}}
| \`{{name}}\`{{#if deprecated}} ⚠️{{/if}} | \`{{escapeType type}}\` | {{#if required}}✓{{else}}-{{/if}} | {{#if defaultValue}}\`{{defaultValue}}\`{{else}}-{{/if}} | {{description}} |
{{/each}}
{{else}}
_This component does not accept any props._
{{/if}}

{{#if slots.length}}
## Slots

{{#each slots}}
- **{{name}}**: {{description}}
{{/each}}
{{/if}}

{{#if events.length}}
## Events

| Event | Description | Payload |
|-------|-------------|---------|
{{#each events}}
| \`{{name}}\` | {{description}} | {{#if payload}}\`{{payload}}\`{{else}}-{{/if}} |
{{/each}}
{{/if}}

## Usage

<Tabs items={[{{#each usage}}'{{title}}'{{#unless @last}}, {{/unless}}{{/each}}]}>
{{#each usage}}
<Tab>
{{#if description}}
{{description}}

{{/if}}
\`\`\`{{language}}
{{formatCode code}}
\`\`\`
</Tab>
{{/each}}
</Tabs>

## Accessibility

{{#with accessibility}}
{{#if role}}
**ARIA Role:** \`{{role}}\`
{{/if}}

{{#if aria.length}}
### ARIA Attributes
{{#each aria}}
- {{this}}
{{/each}}
{{/if}}

{{#if keyboard.length}}
### Keyboard Navigation

| Key | Action |
|-----|--------|
{{#each keyboard}}
| \`{{key}}\` | {{action}} |
{{/each}}
{{/if}}

{{#if notes.length}}
### Notes
{{#each notes}}
- {{this}}
{{/each}}
{{/if}}
{{/with}}

{{#if bestPractices.length}}
## Best Practices

| ✅ Do | ❌ Don't |
|------|---------|
{{#each bestPractices}}
| {{do}} | {{#if dont}}{{dont}}{{else}}-{{/if}} |
{{/each}}
{{/if}}

{{#if suggestions.length}}
## Suggestions for Improvement

{{#each suggestions}}
<Callout type="{{#eq priority 'critical'}}error{{else}}{{#eq priority 'high'}}warning{{else}}info{{/eq}}{{/eq}}">
  **{{upperCase category}}** ({{priority}} priority)

  {{message}}
  {{#if autofix}}

  Suggested fix: \`{{autofix}}\`
  {{/if}}
</Callout>

{{/each}}
{{/if}}

---

<small>
  Generated by AutoDocs on {{metadata.generatedAt}} |
  Model: {{metadata.modelVersion}} |
  [View Source]({{metadata.sourceFile}})
</small>
`;

export class DocumentationRenderer {
  private template: HandlebarsTemplateDelegate;
  private config: Config;

  constructor(config: Config) {
    this.config = config;
    this.template = Handlebars.compile(DEFAULT_TEMPLATE);
  }

  async init(): Promise<void> {
    // Load custom template if specified
    if (this.config.paths.templates) {
      const customPath = path.join(this.config.paths.templates, 'component.hbs');
      try {
        const customTemplate = await fs.readFile(customPath, 'utf-8');
        this.template = Handlebars.compile(customTemplate);
      } catch {
        // Use default template
      }
    }
  }

  render(doc: ComponentDoc): string {
    switch (this.config.output.format) {
      case 'json':
        return JSON.stringify(doc, null, 2);
      case 'md':
        return this.renderMarkdown(doc);
      case 'mdx':
      default:
        return this.renderMDX(doc);
    }
  }

  private renderMDX(doc: ComponentDoc): string {
    return this.template(doc);
  }

  private renderMarkdown(doc: ComponentDoc): string {
    // Simplified markdown without Nextra components
    const mdx = this.template(doc);

    // Strip MDX-specific syntax
    return mdx
      .replace(/import.*from.*;\n/g, '')
      .replace(/<Callout[^>]*>([\s\S]*?)<\/Callout>/g, '> $1')
      .replace(/<Tabs[^>]*>[\s\S]*?<\/Tabs>/g, (match) => {
        // Extract code blocks from tabs
        const codeBlocks = match.match(/```[\s\S]*?```/g) || [];
        return codeBlocks.join('\n\n');
      })
      .replace(/<Tab>/g, '')
      .replace(/<\/Tab>/g, '');
  }

  // Generate a single index file listing all components
  renderIndex(docs: ComponentDoc[]): string {
    const byCategory = docs.reduce((acc, doc) => {
      const cat = doc.category || 'Uncategorized';
      if (!acc[cat]) acc[cat] = [];
      acc[cat].push(doc);
      return acc;
    }, {} as Record<string, ComponentDoc[]>);

    let content = `---
title: Components
description: Component library documentation
---

# Components

`;

    for (const [category, components] of Object.entries(byCategory).sort()) {
      content += `## ${category}\n\n`;

      for (const doc of components.sort((a, b) => a.name.localeCompare(b.name))) {
        content += `- [${doc.displayName || doc.name}](./${doc.name}) - ${doc.description.slice(0, 100)}${doc.description.length > 100 ? '...' : ''}\n`;
      }

      content += '\n';
    }

    return content;
  }
}
